---
title: "R for Marine Science Workshop 1"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
# Set options, housekeeping
knitr::opts_chunk$set(
	echo = FALSE,
	include = TRUE,
	message = FALSE,
	warning = FALSE)
```

## Introduction


### Clear out environment
```{r housekeeping, message=FALSE, warning=FALSE, include=FALSE}
rm(list=ls())
```


### Load packages, penguin data and conduct basic EDA
```{r source-script1, message=FALSE, warning=FALSE, include=FALSE}
source("Workshop1.R")
```

## Explore morphometric relationships
```{r source-script2, message=FALSE, warning=FALSE, include=FALSE}
source("morpho.R")
```

```{r}
# Isolate observations belonging to a single categorical target group
adelie_cohort <- filter(penguins, species == "Adelie")

# Sift out individuals using continuous numerical boundary thresholds
# Preserves only large penguins whose mass exceeds 4500 grams
heavy_penguins <- filter(penguins, body_mass_g > 4500)

# Combine multiple conditional parameters across separate attributes
# Preserves records matching Gentoo penguins sampled explicitly on Biscoe Island
biscoe_gentoo <- filter(penguins, species == "Gentoo" & island == "Biscoe")

# Sift records matching multiple targeting flags within an explicit set
sub_islands <- filter(penguins, island %in% c("Dream", "Torgersen"))

```


```{r}
# Sort penguins by ascending body mass (Default setting: Smallest mass first)
lightest_first <- arrange(penguins, body_mass_g)

# Sort penguins in descending sequence using the desc() layout wrapper
heaviest_first <- arrange(penguins, desc(body_mass_g))

# Execute nested sorting criteria: Group by species, then sort by descending bill length
stratified_morphology <- arrange(penguins, species, desc(bill_length_mm))




```



```{r}
penguins |> 
  group_by(species, island) |>
  summarise(median_body_mass = median(body_mass_g, na.rm = TRUE))

# Box plot of median body mass by species
penguins |> 
  ggplot(aes(x = species, y = body_mass_g, fill = species)) +
  geom_boxplot() +
  theme_minimal()
  
```




```{r}
#penguin_table <- 
  penguins |> 
  group_by(species, island) |>
  summarise(mean_bill_len = mean(bill_length_mm, na.rm = TRUE))

penguin_figure <- 
penguin_table |> 
  ggplot(aes(x = species, y = mean_bill_len, fill = species)) +
  geom_col() +
  theme_minimal()

penguin_table %>% 
penguin_figure
```




